# Generated by Django 5.0.6 on 2024-08-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('moviestore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminlogin',
            new_name='loginlogin',
        ),
    ]
