# Generated by Django 5.0.6 on 2024-08-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('moviestore', '0002_rename_adminlogin_loginlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginlogin',
            new_name='AdminLogin',
        ),
    ]
